from pathlib import Path
p=Path('windows/marshall_stock_v30.py')
s=p.read_text(encoding='utf-8')
s=s.replace('BASE = "https://finance.naver.com"\n', 'BASE = "https://finance.naver.com"\nMARKETINDEX_URL = BASE + "/marketindex/"\n')
needle='''def sentiment(title):\n    p=sum(1 for w in POS_WORDS if w in title); n=sum(1 for w in NEG_WORDS if w in title)\n    return p-n\n\ndef scan_market(progress=None, topn=40):\n'''
repl='''def sentiment(title):\n    p=sum(1 for w in POS_WORDS if w in title); n=sum(1 for w in NEG_WORDS if w in title)\n    return p-n\n\ndef market_environment():\n    """네이버 시장지표를 읽어 환율·달러·금리 환경을 별도 점수화한다."""\n    html=http_text(MARKETINDEX_URL)\n    lp=LinkParser(); lp.feed(html)\n    rp=RowParser(); rp.feed(html)\n    texts=[]\n    wanted=("미국 USD","일본 JPY","유럽연합 EUR","중국 CNY","달러/일본 엔","유로/달러","영국 파운드/달러","달러인덱스","달러 인덱스","WTI","국제 금","국내 금")\n    for href,t in lp.links:\n        t=re.sub(r"\\s+"," ",t).strip()\n        if t and any(k in t for k in wanted) and t not in texts:texts.append(t)\n    rate_rows=[]\n    for cells,links in rp.rows:\n        row=" | ".join(x for x in cells if x)\n        if any(k in row for k in ("CD금리","콜 금리","국고채","회사채","COFIX")):\n            rate_rows.append(row)\n    score=50; reasons=[]\n    def direction_adjust(keys, up_delta, down_delta, label):\n        nonlocal score\n        hit=next((x for x in texts if any(k in x for k in keys)),"")\n        if hit:\n            if "상승" in hit:score+=up_delta; reasons.append(f"{label} 상승 {up_delta:+d}")\n            elif "하락" in hit:score+=down_delta; reasons.append(f"{label} 하락 {down_delta:+d}")\n    direction_adjust(("미국 USD",),-7,+7,"원/달러")\n    direction_adjust(("달러인덱스","달러 인덱스"),-5,+5,"달러인덱스")\n    kr3=next((x for x in rate_rows if "국고채" in x and "3년" in x),"")\n    if kr3:\n        if "상승" in kr3:score-=4;reasons.append("국고채3년 상승 -4")\n        elif "하락" in kr3:score+=4;reasons.append("국고채3년 하락 +4")\n    wti=next((x for x in texts if x.startswith("WTI") or " WTI" in x),"")\n    if wti:\n        if "상승" in wti:score-=1;reasons.append("WTI 상승 -1")\n        elif "하락" in wti:score+=1;reasons.append("WTI 하락 +1")\n    score=max(0,min(100,score))\n    verdict="매우 우호" if score>=65 else "우호" if score>=56 else "중립" if score>=45 else "부담" if score>=35 else "위험회피"\n    return {"score":score,"verdict":verdict,"items":texts[:14],"rates":rate_rows[:10],"reasons":reasons}\n\ndef scan_market(progress=None, topn=40):\n'''
if needle not in s: raise SystemExit('patch anchor 1 missing')
s=s.replace(needle,repl)
s=s.replace('''def scan_market(progress=None, topn=40):\n    cands={}\n''','''def scan_market(progress=None, topn=40):\n    cands={}\n    try:\n        if progress:progress("시장환경(환율·금리·달러) 분석 중...",2)\n        env=market_environment()\n    except Exception:\n        env={"score":50,"verdict":"중립","items":[],"rates":[],"reasons":[]}\n''')
s=s.replace('''            final=m["score"]*.58+source_score*.42\n''','''            final=m["score"]*.58+source_score*.42\n            final=final*.93+env["score"]*.07\n''')
s=s.replace('''            final=max(0,min(100,final));d.update({"name":name if name!=d["code"] else d["name"],"price":price or d["price"],"change":chg,"chart":m["score"],"final":final,"grade":grade(final),"metrics":m})\n''','''            final=max(0,min(100,final));d.update({"name":name if name!=d["code"] else d["name"],"price":price or d["price"],"change":chg,"chart":m["score"],"final":final,"grade":grade(final),"metrics":m,"market_env":env})\n''')
s=s.replace('''            d.update({"chart":0,"final":max(0,min(100,50+d["signal"]*2)),"grade":grade(max(0,min(100,50+d["signal"]*2))),"error":str(e)});results.append(d)\n''','''            fallback=max(0,min(100,(50+d["signal"]*2)*.93+env["score"]*.07));d.update({"chart":0,"final":fallback,"grade":grade(fallback),"market_env":env,"error":str(e)});results.append(d)\n''')
old='''for key,title in [("scan","🚀 초특급 TOP20"),("analysis","🔎 종목 종합분석"),("theme","🔥 테마 레이더"),("flow","💰 외국인·기관 수급"),("news","📰 뉴스·리서치"),("watch","⭐ 관심종목 LIVE"),("portfolio","💼 10억 가상투자"),("diag","🛠 데이터 상태")]:'''
new='''for key,title in [("scan","🚀 초특급 TOP20"),("analysis","🔎 종목 종합분석"),("market","🌍 시장환경"),("theme","🔥 테마 레이더"),("flow","💰 외국인·기관 수급"),("news","📰 뉴스·리서치"),("watch","⭐ 관심종목 LIVE"),("portfolio","💼 10억 가상투자"),("diag","🛠 데이터 상태")]:'''
if old not in s: raise SystemExit('patch anchor tabs missing')
s=s.replace(old,new)
s=s.replace('''self._scan_tab();self._analysis_tab();self._theme_tab();self._flow_tab();self._news_tab();self._watch_tab();self._portfolio_tab();self._diag_tab()''','''self._scan_tab();self._analysis_tab();self._market_tab();self._theme_tab();self._flow_tab();self._news_tab();self._watch_tab();self._portfolio_tab();self._diag_tab()''')
needle2='''    def _theme_tab(self):\n'''
market_method='''    def _market_tab(self):\n        f=self.tabs["market"];bar=tk.Frame(f,bg="#0f172a");bar.pack(fill="x",padx=14,pady=12)\n        self.btn(bar,"🌍 시장환경 새로고침",self.refresh_market_env,True).pack(side="left")\n        tk.Label(bar,text="원/달러 · 달러인덱스 · WTI · 국내금리 → 종목점수와 분리된 시장환경 보조점수",bg="#0f172a",fg="#60a5fa",font=("Malgun Gothic",10)).pack(side="left",padx=14)\n        pan=tk.PanedWindow(f,orient="horizontal",bg="#0f172a",sashwidth=5);pan.pack(fill="both",expand=True,padx=14,pady=(0,14))\n        left=tk.Frame(pan,bg="#0f172a");right=tk.Frame(pan,bg="#0f172a");pan.add(left,minsize=500);pan.add(right,minsize=450)\n        self.market_score=tk.Label(left,text="시장환경 --",bg="#111827",fg="#fbbf24",font=("Malgun Gothic",25,"bold"),pady=18);self.market_score.pack(fill="x")\n        self.market_tree=self.tree(left,["시장지표","현재 상태"],[180,520]);self.market_tree.pack(fill="both",expand=True,pady=(10,0))\n        self.market_text=tk.Text(right,bg="#0b1220",fg="#e5e7eb",font=("Malgun Gothic",11),wrap="word",relief="flat");self.market_text.pack(fill="both",expand=True)\n        self.market_env_cache=None\n    def refresh_market_env(self):\n        self.market_score.config(text="시장환경 분석 중...")\n        self.market_tree.delete(*self.market_tree.get_children());self.market_text.delete("1.0","end")\n        def work():\n            try:env=market_environment();self.market_env_cache=env;self.after(0,lambda:self.fill_market_env(env))\n            except Exception as e:self.after(0,lambda:messagebox.showerror("시장환경",str(e)))\n        threading.Thread(target=work,daemon=True).start()\n    def fill_market_env(self,env):\n        self.market_score.config(text=f"시장환경 {env['score']:.0f}/100 · {env['verdict']}")\n        for x in env["items"]:self.market_tree.insert("","end",values=("환율/원자재",x))\n        for x in env["rates"]:self.market_tree.insert("","end",values=("국내금리",x))\n        reasons="\\n".join("• "+x for x in env["reasons"]) or "• 뚜렷한 가감점 신호 없음"\n        txt=f"[마샬 시장환경 판독]\\n\\n점수 {env['score']:.0f}/100 · {env['verdict']}\\n\\n[점수 근거]\\n{reasons}\\n\\n이 점수는 개별 종목의 차트·수급·테마 강도와 별도로 계산하며, 초특급 TOP20의 최종 진입매력도에 7%만 반영합니다. 환율·금리만으로 종목을 매수/매도하지 않습니다."\n        self.market_text.insert("end",txt);self.refresh_diag()\n\n'''
if needle2 not in s: raise SystemExit('patch anchor market method missing')
s=s.replace(needle2,market_method+needle2,1)
old2='''        self.scan_status.config(text=f"완료 · 후보 {len(r)}개 분석");self.prog.configure(value=100);self.refresh_diag()\n'''
new2='''        env=(r[0].get("market_env") if r else None) or {"score":50,"verdict":"중립"};self.scan_status.config(text=f"완료 · 후보 {len(r)}개 분석 · 시장환경 {env['score']:.0f}({env['verdict']})");self.prog.configure(value=100);self.refresh_diag()\n'''
if old2 not in s: raise SystemExit('patch anchor finish missing')
s=s.replace(old2,new2)
p.write_text(s,encoding='utf-8')
print('v3.1 market environment patch applied')
